[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Desh Diesh <danika_asus@eustace.io>"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"